name: Push released code
on:
  push:
    tags:
    - v*

env:
  SLOCTL_VERSION: "0.0.72"

jobs:
  push-screeps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Push the code
      id: myaction
      uses: kskitek/screeps-pusher@v0.1
      with:
        branch: main
        token: ${{ secrets.token }}

  apply-slos:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Download sloctl
      run: |-
        echo "Downloading sloctl $SLOCTL_VERSION"
        wget https://github.com/nobl9/sloctl/raw/main/sloctl-linux-$SLOCTL_VERSION.zip -O sloctl.zip
        unzip sloctl.zip

    - name: Setup config.toml
      run: |-
        mkdir -p ~/.config/nobl9
        echo "${{ secrets.config_toml }}" | base64 -d > ~/.config/nobl9/config.toml

    - name: Test sloctl
      run: ./sloctl get slo -p screeps > /dev/null

    - name: Apply SLOs
      run: slos/push.sh

    - name: Annotate SLOs
      env:
        RELEASE: ${{ github.ref_name }}
      run: slos/annotations.sh
